### ISSUE TITLE
Multiple messages under the same "Item"

### ISSUE THREAD

**Issue by GrimChip** [jerpa/node-red-contrib-mios#3]
Hi, so I am trying to pull just the KWH from a energy monitor and do a simple chart with it but when I enter the item I get several other topics with it.  

The topic I would like to get is just "topic: "Common:Energy Monitor Total:KWH"" but mios is also sending topic: "Common:Energy Monitor Total:KWHReading" as well as others from the device.  Is there anyway to stop it from getting the other values?

![capture](https://user-images.githubusercontent.com/42618344/44479905-6ef5a200-a631-11e8-896b-9e305d92989c.PNG)

**Comment by jerpa** [comment]
Right now it matches every item that starts with the string you entered. I think a god solution is to include an option for "exact match". 
So until I have done that, one solution is to put a switch node right after your miosIN that acts as a filter on msg.topic=="Common:Energy Monitor Total:KWH".

I leave this issue open until the option is added.

**Comment by jerpa** [comment]
Added a checkbox in the in item to do an exact match instead of just the beginning.
