### ISSUE TITLE
Apostrophe in item names

### ISSUE THREAD

**Issue by nodecentral** [jerpa/node-red-contrib-mios#4]
Hi, I’m having issues returning variable values when the item has an apostrophe in its room and device name.

The following do not return anything.

Bob’s Room:Bob’s Room Temperature:CurrentTemperature
Jill’s Room:Jill’s Room Temperature:CurrentTemperature

Whereas these do.

Loft:Loft Temperature:CurrentTemperature
Kitchen:Kitchen Temperature:CurrentTemperature

Any ideas ?

**Comment by jerpa** [comment]
I tried to reproduce it by copying your example name and it works for me. All the mappings are taken from http://x.x.x.x:3480/data_request?id=user_data where x.x.x.x is the ip of your Mios unit. If you take the results of that request and paste it into for example [https://jsonformatter.org/](https://jsonformatter.org/) you might see which name it gets there?

**Comment by nodecentral** [comment]
Thanks so much for responding, I checked the Vera UI and the device names are clearly there, but they are not in that user_data url.

Found them !! For some reason they are recorded as follows.

Bob€™s Room Temperature
Jillâ€™s Room Temperature
