### ISSUE TITLE
TargetColor 

### ISSUE THREAD

**Issue by blazarmilkywayflybee** [jerpa/node-red-contrib-mios#7]
No matter how I format this string I'm receiving the following error in response.

**"TypeError: node.info is not a function"**

I am able to set the status and targetload on the light just fine in the same manner.

edit: I see there is no reference to urn:micasaverde-com:serviceId:Color1! That will do it. I might see if I have any luck adding this.

**Comment by jerpa** [comment]
Is this fixed in your fork? If so, please to a merge it back here. I have no items with color so I can't test it.

**Comment by blazarmilkywayflybee** [comment]
Does everything I need from my end, so I'll call that fixed.
